//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADSMS.DataAccess
{
    using System;
    
    public partial class getChartbyItem_Result
    {
        public string ItemDescription { get; set; }
        public Nullable<int> QuantReq { get; set; }
        public Nullable<System.DateTime> DisbCreateDate { get; set; }
        public string DepName { get; set; }
    }
}
