//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADSMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class collectionPoint
    {
        public collectionPoint()
        {
            this.departments = new HashSet<department>();
        }
    
        public int CollectionPointID { get; set; }
        public string CollectionPointName { get; set; }
        public string CollectionPointAddress { get; set; }
        public string CollectionPointTime { get; set; }
        public string CollectionPointDate { get; set; }
    
        public virtual collectionPoint collectionPoint1 { get; set; }
        public virtual collectionPoint collectionPoint2 { get; set; }
        public virtual ICollection<department> departments { get; set; }
    }
}
