//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADSMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class delegation
    {
        public int DelgID { get; set; }
        public int DelgEmpID { get; set; }
        public System.DateTime DelgFromDate { get; set; }
        public System.DateTime DelgToDate { get; set; }
        public string DelgStatus { get; set; }
        public int DelApproveEmpID { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
    }
}
