//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADSMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class disbursement
    {
        public int DisbID { get; set; }
        public int DisbDepID { get; set; }
        public string DisbStatus { get; set; }
        public Nullable<System.DateTime> DisbReceiveDate { get; set; }
        public Nullable<System.DateTime> DisbCreateDate { get; set; }
    
        public virtual department department { get; set; }
    }
}
