//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADSMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class requisitiondetail
    {
        public int ReqID { get; set; }
        public int ReqItemID { get; set; }
        public int ReqQuantityReq { get; set; }
        public string ReqStatus { get; set; }
    
        public virtual item item { get; set; }
        public virtual requisition requisition { get; set; }
    }
}
