//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADSMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class requisition
    {
        public requisition()
        {
            this.requisitiondetails = new HashSet<requisitiondetail>();
        }
    
        public int ReqID { get; set; }
        public int ReqEmpId { get; set; }
        public string ReqStatus { get; set; }
        public System.DateTime ReqDate { get; set; }
        public Nullable<System.DateTime> ReqApproveDate { get; set; }
        public string ReqReason { get; set; }
        public Nullable<int> ReqApproveEmpID { get; set; }
        public int ReqDepID { get; set; }
    
        public virtual department department { get; set; }
        public virtual employee employee { get; set; }
        public virtual employee employee1 { get; set; }
        public virtual ICollection<requisitiondetail> requisitiondetails { get; set; }
    }
}
