//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADSMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public role()
        {
            this.employees = new HashSet<employee>();
            this.storeemps = new HashSet<storeemp>();
            this.users = new HashSet<user>();
        }
    
        public int RoleID { get; set; }
        public string RoleName { get; set; }
    
        public virtual ICollection<employee> employees { get; set; }
        public virtual ICollection<storeemp> storeemps { get; set; }
        public virtual ICollection<user> users { get; set; }
    }
}
