//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADSMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class storeemp
    {
        public storeemp()
        {
            this.adjustmentvouchers = new HashSet<adjustmentvoucher>();
            this.adjustmentvouchers1 = new HashSet<adjustmentvoucher>();
            this.purchaseorders = new HashSet<purchaseorder>();
            this.transactions = new HashSet<transaction>();
        }
    
        public int StoreEmpID { get; set; }
        public string StoreEmpName { get; set; }
        public int StoreEmpContact { get; set; }
        public string StoreEmpEmail { get; set; }
        public int StoreEmpRoleID { get; set; }
    
        public virtual ICollection<adjustmentvoucher> adjustmentvouchers { get; set; }
        public virtual ICollection<adjustmentvoucher> adjustmentvouchers1 { get; set; }
        public virtual ICollection<purchaseorder> purchaseorders { get; set; }
        public virtual role role { get; set; }
        public virtual ICollection<transaction> transactions { get; set; }
    }
}
