//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADSMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier
    {
        public supplier()
        {
            this.itemsuppliers = new HashSet<itemsupplier>();
            this.purchaseorders = new HashSet<purchaseorder>();
        }
    
        public int SupplierID { get; set; }
        public string SupplierCode { get; set; }
        public string SupplierName { get; set; }
        public string SupplierContactName { get; set; }
        public int SupplierContactNumber { get; set; }
        public string SupplierContactAddress { get; set; }
        public int SupplierFax { get; set; }
        public string SupplierGSTRegNumber { get; set; }
        public string SupplierEmail { get; set; }
        public int SupplierCollectionPointID { get; set; }
    
        public virtual ICollection<itemsupplier> itemsuppliers { get; set; }
        public virtual ICollection<purchaseorder> purchaseorders { get; set; }
    }
}
