//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADSMS.DataAccess
{
    using System;
    
    public partial class getReqbyDep_Result
    {
        public int DepID { get; set; }
        public string ItemDescription { get; set; }
        public string DepName { get; set; }
        public Nullable<int> Required_Quantity { get; set; }
    }
}
