//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADSMS.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class itemsupplier
    {
        public int SupplierID { get; set; }
        public int ItemID { get; set; }
        public double Price { get; set; }
        public int SupplierRank { get; set; }
    
        public virtual item item { get; set; }
        public virtual supplier supplier { get; set; }
    }
}
